// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: tagFileSystempb/tagFileSystem.proto

package tagFileSystempb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	File []byte   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *TagFile) Reset() {
	*x = TagFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagFile) ProtoMessage() {}

func (x *TagFile) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagFile.ProtoReflect.Descriptor instead.
func (*TagFile) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{0}
}

func (x *TagFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagFile) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *TagFile) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Implementar lo necesario para agregar archivos
type AddFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File *TagFile `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *AddFilesRequest) Reset() {
	*x = AddFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFilesRequest) ProtoMessage() {}

func (x *AddFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFilesRequest.ProtoReflect.Descriptor instead.
func (*AddFilesRequest) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{1}
}

func (x *AddFilesRequest) GetFile() *TagFile {
	if x != nil {
		return x.File
	}
	return nil
}

type AddFilesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *AddFilesResponse) Reset() {
	*x = AddFilesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFilesResponse) ProtoMessage() {}

func (x *AddFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFilesResponse.ProtoReflect.Descriptor instead.
func (*AddFilesResponse) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{2}
}

func (x *AddFilesResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// Implementar lo necesario para eliminar archivos
type DeleteFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag []string `protobuf:"bytes,1,rep,name=tag,proto3" json:"tag,omitempty"`
}

func (x *DeleteFilesRequest) Reset() {
	*x = DeleteFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilesRequest) ProtoMessage() {}

func (x *DeleteFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilesRequest.ProtoReflect.Descriptor instead.
func (*DeleteFilesRequest) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFilesRequest) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

type DeleteFilesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *DeleteFilesResponse) Reset() {
	*x = DeleteFilesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilesResponse) ProtoMessage() {}

func (x *DeleteFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilesResponse.ProtoReflect.Descriptor instead.
func (*DeleteFilesResponse) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFilesResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// Implementar lo necesario para listar a los archivos
type ListFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag []string `protobuf:"bytes,1,rep,name=tag,proto3" json:"tag,omitempty"`
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilesRequest) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

type ListFilesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tags []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{6}
}

func (x *ListFilesResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListFilesResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaqQuery []string `protobuf:"bytes,1,rep,name=taq_query,json=taqQuery,proto3" json:"taq_query,omitempty"`
	TagList  []string `protobuf:"bytes,2,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`
}

func (x *AddTagsRequest) Reset() {
	*x = AddTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagsRequest) ProtoMessage() {}

func (x *AddTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagsRequest.ProtoReflect.Descriptor instead.
func (*AddTagsRequest) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{7}
}

func (x *AddTagsRequest) GetTaqQuery() []string {
	if x != nil {
		return x.TaqQuery
	}
	return nil
}

func (x *AddTagsRequest) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

type AddTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *AddTagsResponse) Reset() {
	*x = AddTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagsResponse) ProtoMessage() {}

func (x *AddTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagsResponse.ProtoReflect.Descriptor instead.
func (*AddTagsResponse) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{8}
}

func (x *AddTagsResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// Implementar lo necesario para eliminar etiquetas
type DeleteTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaqQuery []string `protobuf:"bytes,1,rep,name=taq_query,json=taqQuery,proto3" json:"taq_query,omitempty"`
	TagList  []string `protobuf:"bytes,2,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`
}

func (x *DeleteTagsRequest) Reset() {
	*x = DeleteTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagsRequest) ProtoMessage() {}

func (x *DeleteTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagsRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagsRequest) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTagsRequest) GetTaqQuery() []string {
	if x != nil {
		return x.TaqQuery
	}
	return nil
}

func (x *DeleteTagsRequest) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

type DeleteTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *DeleteTagsResponse) Reset() {
	*x = DeleteTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagsResponse) ProtoMessage() {}

func (x *DeleteTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tagFileSystempb_tagFileSystem_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagsResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagsResponse) Descriptor() ([]byte, []int) {
	return file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTagsResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_tagFileSystempb_tagFileSystem_proto protoreflect.FileDescriptor

var file_tagFileSystempb_tagFileSystem_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x70,
	0x62, 0x2f, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x45,
	0x0a, 0x07, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x37, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x2e, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x2e,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x31, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x0a, 0x10, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22,
	0x3b, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x48, 0x0a, 0x0e,
	0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x61, 0x71, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x61, 0x71, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x74,
	0x61, 0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61,
	0x71, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x74,
	0x61, 0x71, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x30, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xfa, 0x02, 0x0a, 0x14, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a,
	0x08, 0x41, 0x64, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x67, 0x46,
	0x69, 0x6c, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x41, 0x64,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x12, 0x4a, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x12, 0x1b, 0x2e, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46,
	0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x74, 0x61,
	0x67, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67,
	0x73, 0x12, 0x17, 0x2e, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x54,
	0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x61, 0x67,
	0x46, 0x69, 0x6c, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x47, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1a, 0x2e, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tagFileSystempb_tagFileSystem_proto_rawDescOnce sync.Once
	file_tagFileSystempb_tagFileSystem_proto_rawDescData = file_tagFileSystempb_tagFileSystem_proto_rawDesc
)

func file_tagFileSystempb_tagFileSystem_proto_rawDescGZIP() []byte {
	file_tagFileSystempb_tagFileSystem_proto_rawDescOnce.Do(func() {
		file_tagFileSystempb_tagFileSystem_proto_rawDescData = protoimpl.X.CompressGZIP(file_tagFileSystempb_tagFileSystem_proto_rawDescData)
	})
	return file_tagFileSystempb_tagFileSystem_proto_rawDescData
}

var file_tagFileSystempb_tagFileSystem_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tagFileSystempb_tagFileSystem_proto_goTypes = []interface{}{
	(*TagFile)(nil),             // 0: tagFile.tagFile
	(*AddFilesRequest)(nil),     // 1: tagFile.AddFilesRequest
	(*AddFilesResponse)(nil),    // 2: tagFile.AddFilesResponse
	(*DeleteFilesRequest)(nil),  // 3: tagFile.DeleteFilesRequest
	(*DeleteFilesResponse)(nil), // 4: tagFile.DeleteFilesResponse
	(*ListFilesRequest)(nil),    // 5: tagFile.ListFilesRequest
	(*ListFilesResponse)(nil),   // 6: tagFile.ListFilesResponse
	(*AddTagsRequest)(nil),      // 7: tagFile.AddTagsRequest
	(*AddTagsResponse)(nil),     // 8: tagFile.AddTagsResponse
	(*DeleteTagsRequest)(nil),   // 9: tagFile.DeleteTagsRequest
	(*DeleteTagsResponse)(nil),  // 10: tagFile.DeleteTagsResponse
}
var file_tagFileSystempb_tagFileSystem_proto_depIdxs = []int32{
	0,  // 0: tagFile.AddFilesRequest.file:type_name -> tagFile.tagFile
	1,  // 1: tagFile.tagFileSystemService.AddFiles:input_type -> tagFile.AddFilesRequest
	3,  // 2: tagFile.tagFileSystemService.DeleteFiles:input_type -> tagFile.DeleteFilesRequest
	5,  // 3: tagFile.tagFileSystemService.ListFiles:input_type -> tagFile.ListFilesRequest
	7,  // 4: tagFile.tagFileSystemService.AddTags:input_type -> tagFile.AddTagsRequest
	9,  // 5: tagFile.tagFileSystemService.DeleteTags:input_type -> tagFile.DeleteTagsRequest
	2,  // 6: tagFile.tagFileSystemService.AddFiles:output_type -> tagFile.AddFilesResponse
	4,  // 7: tagFile.tagFileSystemService.DeleteFiles:output_type -> tagFile.DeleteFilesResponse
	6,  // 8: tagFile.tagFileSystemService.ListFiles:output_type -> tagFile.ListFilesResponse
	8,  // 9: tagFile.tagFileSystemService.AddTags:output_type -> tagFile.AddTagsResponse
	10, // 10: tagFile.tagFileSystemService.DeleteTags:output_type -> tagFile.DeleteTagsResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_tagFileSystempb_tagFileSystem_proto_init() }
func file_tagFileSystempb_tagFileSystem_proto_init() {
	if File_tagFileSystempb_tagFileSystem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFilesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFilesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFilesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tagFileSystempb_tagFileSystem_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tagFileSystempb_tagFileSystem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tagFileSystempb_tagFileSystem_proto_goTypes,
		DependencyIndexes: file_tagFileSystempb_tagFileSystem_proto_depIdxs,
		MessageInfos:      file_tagFileSystempb_tagFileSystem_proto_msgTypes,
	}.Build()
	File_tagFileSystempb_tagFileSystem_proto = out.File
	file_tagFileSystempb_tagFileSystem_proto_rawDesc = nil
	file_tagFileSystempb_tagFileSystem_proto_goTypes = nil
	file_tagFileSystempb_tagFileSystem_proto_depIdxs = nil
}
