// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/proto/chord.proto

package chord

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Objetos del Chord
// Nodo que contiene una ID y una direccion IP.
type Node struct {
	ID                   []byte   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Node) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Node) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

// Objeto que representa el archivo que se esta mandando
type TagFile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Extension            string   `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
	File                 []byte   `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagFile) Reset()         { *m = TagFile{} }
func (m *TagFile) String() string { return proto.CompactTextString(m) }
func (*TagFile) ProtoMessage()    {}
func (*TagFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{1}
}

func (m *TagFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagFile.Unmarshal(m, b)
}
func (m *TagFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagFile.Marshal(b, m, deterministic)
}
func (m *TagFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagFile.Merge(m, src)
}
func (m *TagFile) XXX_Size() int {
	return xxx_messageInfo_TagFile.Size(m)
}
func (m *TagFile) XXX_DiscardUnknown() {
	xxx_messageInfo_TagFile.DiscardUnknown(m)
}

var xxx_messageInfo_TagFile proto.InternalMessageInfo

func (m *TagFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TagFile) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *TagFile) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *TagFile) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type TagEncoder struct {
	FileName             string   `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileExtension        string   `protobuf:"bytes,2,opt,name=FileExtension,proto3" json:"FileExtension,omitempty"`
	NodeID               []byte   `protobuf:"bytes,3,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	NodeIP               string   `protobuf:"bytes,4,opt,name=NodeIP,proto3" json:"NodeIP,omitempty"`
	NodePort             string   `protobuf:"bytes,5,opt,name=NodePort,proto3" json:"NodePort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagEncoder) Reset()         { *m = TagEncoder{} }
func (m *TagEncoder) String() string { return proto.CompactTextString(m) }
func (*TagEncoder) ProtoMessage()    {}
func (*TagEncoder) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{2}
}

func (m *TagEncoder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagEncoder.Unmarshal(m, b)
}
func (m *TagEncoder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagEncoder.Marshal(b, m, deterministic)
}
func (m *TagEncoder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagEncoder.Merge(m, src)
}
func (m *TagEncoder) XXX_Size() int {
	return xxx_messageInfo_TagEncoder.Size(m)
}
func (m *TagEncoder) XXX_DiscardUnknown() {
	xxx_messageInfo_TagEncoder.DiscardUnknown(m)
}

var xxx_messageInfo_TagEncoder proto.InternalMessageInfo

func (m *TagEncoder) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *TagEncoder) GetFileExtension() string {
	if m != nil {
		return m.FileExtension
	}
	return ""
}

func (m *TagEncoder) GetNodeID() []byte {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *TagEncoder) GetNodeIP() string {
	if m != nil {
		return m.NodeIP
	}
	return ""
}

func (m *TagEncoder) GetNodePort() string {
	if m != nil {
		return m.NodePort
	}
	return ""
}

// Las Request vacias
type GetPredecessorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPredecessorRequest) Reset()         { *m = GetPredecessorRequest{} }
func (m *GetPredecessorRequest) String() string { return proto.CompactTextString(m) }
func (*GetPredecessorRequest) ProtoMessage()    {}
func (*GetPredecessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{3}
}

func (m *GetPredecessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPredecessorRequest.Unmarshal(m, b)
}
func (m *GetPredecessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPredecessorRequest.Marshal(b, m, deterministic)
}
func (m *GetPredecessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPredecessorRequest.Merge(m, src)
}
func (m *GetPredecessorRequest) XXX_Size() int {
	return xxx_messageInfo_GetPredecessorRequest.Size(m)
}
func (m *GetPredecessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPredecessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPredecessorRequest proto.InternalMessageInfo

type GetSuccessorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSuccessorRequest) Reset()         { *m = GetSuccessorRequest{} }
func (m *GetSuccessorRequest) String() string { return proto.CompactTextString(m) }
func (*GetSuccessorRequest) ProtoMessage()    {}
func (*GetSuccessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{4}
}

func (m *GetSuccessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSuccessorRequest.Unmarshal(m, b)
}
func (m *GetSuccessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSuccessorRequest.Marshal(b, m, deterministic)
}
func (m *GetSuccessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuccessorRequest.Merge(m, src)
}
func (m *GetSuccessorRequest) XXX_Size() int {
	return xxx_messageInfo_GetSuccessorRequest.Size(m)
}
func (m *GetSuccessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuccessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuccessorRequest proto.InternalMessageInfo

type CheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{5}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

type PartitionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionRequest) Reset()         { *m = PartitionRequest{} }
func (m *PartitionRequest) String() string { return proto.CompactTextString(m) }
func (*PartitionRequest) ProtoMessage()    {}
func (*PartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{6}
}

func (m *PartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionRequest.Unmarshal(m, b)
}
func (m *PartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionRequest.Marshal(b, m, deterministic)
}
func (m *PartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionRequest.Merge(m, src)
}
func (m *PartitionRequest) XXX_Size() int {
	return xxx_messageInfo_PartitionRequest.Size(m)
}
func (m *PartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionRequest proto.InternalMessageInfo

type ExtendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtendResponse) Reset()         { *m = ExtendResponse{} }
func (m *ExtendResponse) String() string { return proto.CompactTextString(m) }
func (*ExtendResponse) ProtoMessage()    {}
func (*ExtendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{7}
}

func (m *ExtendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtendResponse.Unmarshal(m, b)
}
func (m *ExtendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtendResponse.Marshal(b, m, deterministic)
}
func (m *ExtendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtendResponse.Merge(m, src)
}
func (m *ExtendResponse) XXX_Size() int {
	return xxx_messageInfo_ExtendResponse.Size(m)
}
func (m *ExtendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExtendResponse proto.InternalMessageInfo

// Las respuestas vacias
type SetPredecessorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPredecessorResponse) Reset()         { *m = SetPredecessorResponse{} }
func (m *SetPredecessorResponse) String() string { return proto.CompactTextString(m) }
func (*SetPredecessorResponse) ProtoMessage()    {}
func (*SetPredecessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{8}
}

func (m *SetPredecessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPredecessorResponse.Unmarshal(m, b)
}
func (m *SetPredecessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPredecessorResponse.Marshal(b, m, deterministic)
}
func (m *SetPredecessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPredecessorResponse.Merge(m, src)
}
func (m *SetPredecessorResponse) XXX_Size() int {
	return xxx_messageInfo_SetPredecessorResponse.Size(m)
}
func (m *SetPredecessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPredecessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPredecessorResponse proto.InternalMessageInfo

type SetSuccessorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSuccessorResponse) Reset()         { *m = SetSuccessorResponse{} }
func (m *SetSuccessorResponse) String() string { return proto.CompactTextString(m) }
func (*SetSuccessorResponse) ProtoMessage()    {}
func (*SetSuccessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{9}
}

func (m *SetSuccessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSuccessorResponse.Unmarshal(m, b)
}
func (m *SetSuccessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSuccessorResponse.Marshal(b, m, deterministic)
}
func (m *SetSuccessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSuccessorResponse.Merge(m, src)
}
func (m *SetSuccessorResponse) XXX_Size() int {
	return xxx_messageInfo_SetSuccessorResponse.Size(m)
}
func (m *SetSuccessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSuccessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetSuccessorResponse proto.InternalMessageInfo

type NotifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyResponse) Reset()         { *m = NotifyResponse{} }
func (m *NotifyResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyResponse) ProtoMessage()    {}
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{10}
}

func (m *NotifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyResponse.Unmarshal(m, b)
}
func (m *NotifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyResponse.Marshal(b, m, deterministic)
}
func (m *NotifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyResponse.Merge(m, src)
}
func (m *NotifyResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyResponse.Size(m)
}
func (m *NotifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyResponse proto.InternalMessageInfo

type CheckResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{11}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

type SetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{12}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{13}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type DiscardResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardResponse) Reset()         { *m = DiscardResponse{} }
func (m *DiscardResponse) String() string { return proto.CompactTextString(m) }
func (*DiscardResponse) ProtoMessage()    {}
func (*DiscardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{14}
}

func (m *DiscardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardResponse.Unmarshal(m, b)
}
func (m *DiscardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardResponse.Marshal(b, m, deterministic)
}
func (m *DiscardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardResponse.Merge(m, src)
}
func (m *DiscardResponse) XXX_Size() int {
	return xxx_messageInfo_DiscardResponse.Size(m)
}
func (m *DiscardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardResponse proto.InternalMessageInfo

// Las request que pasan un nodo
type SetPredecessorRequest struct {
	Predecessor          *Node    `protobuf:"bytes,1,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPredecessorRequest) Reset()         { *m = SetPredecessorRequest{} }
func (m *SetPredecessorRequest) String() string { return proto.CompactTextString(m) }
func (*SetPredecessorRequest) ProtoMessage()    {}
func (*SetPredecessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{15}
}

func (m *SetPredecessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPredecessorRequest.Unmarshal(m, b)
}
func (m *SetPredecessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPredecessorRequest.Marshal(b, m, deterministic)
}
func (m *SetPredecessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPredecessorRequest.Merge(m, src)
}
func (m *SetPredecessorRequest) XXX_Size() int {
	return xxx_messageInfo_SetPredecessorRequest.Size(m)
}
func (m *SetPredecessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPredecessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPredecessorRequest proto.InternalMessageInfo

func (m *SetPredecessorRequest) GetPredecessor() *Node {
	if m != nil {
		return m.Predecessor
	}
	return nil
}

type SetSuccessorRequest struct {
	Successor            *Node    `protobuf:"bytes,1,opt,name=successor,proto3" json:"successor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSuccessorRequest) Reset()         { *m = SetSuccessorRequest{} }
func (m *SetSuccessorRequest) String() string { return proto.CompactTextString(m) }
func (*SetSuccessorRequest) ProtoMessage()    {}
func (*SetSuccessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{16}
}

func (m *SetSuccessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSuccessorRequest.Unmarshal(m, b)
}
func (m *SetSuccessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSuccessorRequest.Marshal(b, m, deterministic)
}
func (m *SetSuccessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSuccessorRequest.Merge(m, src)
}
func (m *SetSuccessorRequest) XXX_Size() int {
	return xxx_messageInfo_SetSuccessorRequest.Size(m)
}
func (m *SetSuccessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSuccessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSuccessorRequest proto.InternalMessageInfo

func (m *SetSuccessorRequest) GetSuccessor() *Node {
	if m != nil {
		return m.Successor
	}
	return nil
}

type NotifyRequest struct {
	Notify               *Node    `protobuf:"bytes,1,opt,name=notify,proto3" json:"notify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRequest) Reset()         { *m = NotifyRequest{} }
func (m *NotifyRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyRequest) ProtoMessage()    {}
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{17}
}

func (m *NotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRequest.Unmarshal(m, b)
}
func (m *NotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRequest.Marshal(b, m, deterministic)
}
func (m *NotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRequest.Merge(m, src)
}
func (m *NotifyRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyRequest.Size(m)
}
func (m *NotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRequest proto.InternalMessageInfo

func (m *NotifyRequest) GetNotify() *Node {
	if m != nil {
		return m.Notify
	}
	return nil
}

//Las respuestas que devuelven un nodo
type GetPredecessorResponse struct {
	Predecessor          *Node    `protobuf:"bytes,1,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPredecessorResponse) Reset()         { *m = GetPredecessorResponse{} }
func (m *GetPredecessorResponse) String() string { return proto.CompactTextString(m) }
func (*GetPredecessorResponse) ProtoMessage()    {}
func (*GetPredecessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{18}
}

func (m *GetPredecessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPredecessorResponse.Unmarshal(m, b)
}
func (m *GetPredecessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPredecessorResponse.Marshal(b, m, deterministic)
}
func (m *GetPredecessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPredecessorResponse.Merge(m, src)
}
func (m *GetPredecessorResponse) XXX_Size() int {
	return xxx_messageInfo_GetPredecessorResponse.Size(m)
}
func (m *GetPredecessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPredecessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPredecessorResponse proto.InternalMessageInfo

func (m *GetPredecessorResponse) GetPredecessor() *Node {
	if m != nil {
		return m.Predecessor
	}
	return nil
}

type GetSuccessorResponse struct {
	Successor            *Node    `protobuf:"bytes,1,opt,name=successor,proto3" json:"successor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSuccessorResponse) Reset()         { *m = GetSuccessorResponse{} }
func (m *GetSuccessorResponse) String() string { return proto.CompactTextString(m) }
func (*GetSuccessorResponse) ProtoMessage()    {}
func (*GetSuccessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{19}
}

func (m *GetSuccessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSuccessorResponse.Unmarshal(m, b)
}
func (m *GetSuccessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSuccessorResponse.Marshal(b, m, deterministic)
}
func (m *GetSuccessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuccessorResponse.Merge(m, src)
}
func (m *GetSuccessorResponse) XXX_Size() int {
	return xxx_messageInfo_GetSuccessorResponse.Size(m)
}
func (m *GetSuccessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuccessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuccessorResponse proto.InternalMessageInfo

func (m *GetSuccessorResponse) GetSuccessor() *Node {
	if m != nil {
		return m.Successor
	}
	return nil
}

type FindSuccesorResponse struct {
	Succesor             *Node    `protobuf:"bytes,1,opt,name=succesor,proto3" json:"succesor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSuccesorResponse) Reset()         { *m = FindSuccesorResponse{} }
func (m *FindSuccesorResponse) String() string { return proto.CompactTextString(m) }
func (*FindSuccesorResponse) ProtoMessage()    {}
func (*FindSuccesorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{20}
}

func (m *FindSuccesorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSuccesorResponse.Unmarshal(m, b)
}
func (m *FindSuccesorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSuccesorResponse.Marshal(b, m, deterministic)
}
func (m *FindSuccesorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSuccesorResponse.Merge(m, src)
}
func (m *FindSuccesorResponse) XXX_Size() int {
	return xxx_messageInfo_FindSuccesorResponse.Size(m)
}
func (m *FindSuccesorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSuccesorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindSuccesorResponse proto.InternalMessageInfo

func (m *FindSuccesorResponse) GetSuccesor() *Node {
	if m != nil {
		return m.Succesor
	}
	return nil
}

// Otras Request
type FindSuccesorRequest struct {
	ID                   []byte   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSuccesorRequest) Reset()         { *m = FindSuccesorRequest{} }
func (m *FindSuccesorRequest) String() string { return proto.CompactTextString(m) }
func (*FindSuccesorRequest) ProtoMessage()    {}
func (*FindSuccesorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{21}
}

func (m *FindSuccesorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSuccesorRequest.Unmarshal(m, b)
}
func (m *FindSuccesorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSuccesorRequest.Marshal(b, m, deterministic)
}
func (m *FindSuccesorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSuccesorRequest.Merge(m, src)
}
func (m *FindSuccesorRequest) XXX_Size() int {
	return xxx_messageInfo_FindSuccesorRequest.Size(m)
}
func (m *FindSuccesorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSuccesorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindSuccesorRequest proto.InternalMessageInfo

func (m *FindSuccesorRequest) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

// ExtendRequest contains the <key, value> pairs to set on the storage.
type ExtendRequest struct {
	Files                []*TagFile        `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
	Tags                 map[string][]byte `protobuf:"bytes,2,rep,name=Tags,proto3" json:"Tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExtendRequest) Reset()         { *m = ExtendRequest{} }
func (m *ExtendRequest) String() string { return proto.CompactTextString(m) }
func (*ExtendRequest) ProtoMessage()    {}
func (*ExtendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{22}
}

func (m *ExtendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtendRequest.Unmarshal(m, b)
}
func (m *ExtendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtendRequest.Marshal(b, m, deterministic)
}
func (m *ExtendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtendRequest.Merge(m, src)
}
func (m *ExtendRequest) XXX_Size() int {
	return xxx_messageInfo_ExtendRequest.Size(m)
}
func (m *ExtendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExtendRequest proto.InternalMessageInfo

func (m *ExtendRequest) GetFiles() []*TagFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *ExtendRequest) GetTags() map[string][]byte {
	if m != nil {
		return m.Tags
	}
	return nil
}

// DiscardRequest contains the lower and upper bound of the interval storage to delete.
type DiscardRequest struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Files                []string `protobuf:"bytes,2,rep,name=Files,proto3" json:"Files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardRequest) Reset()         { *m = DiscardRequest{} }
func (m *DiscardRequest) String() string { return proto.CompactTextString(m) }
func (*DiscardRequest) ProtoMessage()    {}
func (*DiscardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{23}
}

func (m *DiscardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardRequest.Unmarshal(m, b)
}
func (m *DiscardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardRequest.Marshal(b, m, deterministic)
}
func (m *DiscardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardRequest.Merge(m, src)
}
func (m *DiscardRequest) XXX_Size() int {
	return xxx_messageInfo_DiscardRequest.Size(m)
}
func (m *DiscardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardRequest proto.InternalMessageInfo

func (m *DiscardRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *DiscardRequest) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

// PartitionResponse contains the contains the <key, value> pairs to return.
type PartitionResponse struct {
	InFiles              []*TagFile        `protobuf:"bytes,1,rep,name=InFiles,proto3" json:"InFiles,omitempty"`
	OutFiles             []*TagFile        `protobuf:"bytes,2,rep,name=OutFiles,proto3" json:"OutFiles,omitempty"`
	InTags               map[string][]byte `protobuf:"bytes,3,rep,name=InTags,proto3" json:"InTags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OutTags              map[string][]byte `protobuf:"bytes,4,rep,name=OutTags,proto3" json:"OutTags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PartitionResponse) Reset()         { *m = PartitionResponse{} }
func (m *PartitionResponse) String() string { return proto.CompactTextString(m) }
func (*PartitionResponse) ProtoMessage()    {}
func (*PartitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{24}
}

func (m *PartitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionResponse.Unmarshal(m, b)
}
func (m *PartitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionResponse.Marshal(b, m, deterministic)
}
func (m *PartitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionResponse.Merge(m, src)
}
func (m *PartitionResponse) XXX_Size() int {
	return xxx_messageInfo_PartitionResponse.Size(m)
}
func (m *PartitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionResponse proto.InternalMessageInfo

func (m *PartitionResponse) GetInFiles() []*TagFile {
	if m != nil {
		return m.InFiles
	}
	return nil
}

func (m *PartitionResponse) GetOutFiles() []*TagFile {
	if m != nil {
		return m.OutFiles
	}
	return nil
}

func (m *PartitionResponse) GetInTags() map[string][]byte {
	if m != nil {
		return m.InTags
	}
	return nil
}

func (m *PartitionResponse) GetOutTags() map[string][]byte {
	if m != nil {
		return m.OutTags
	}
	return nil
}

type EditFileFromTagRequest struct {
	Tag                  string      `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Mod                  *TagEncoder `protobuf:"bytes,2,opt,name=Mod,proto3" json:"Mod,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EditFileFromTagRequest) Reset()         { *m = EditFileFromTagRequest{} }
func (m *EditFileFromTagRequest) String() string { return proto.CompactTextString(m) }
func (*EditFileFromTagRequest) ProtoMessage()    {}
func (*EditFileFromTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{25}
}

func (m *EditFileFromTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditFileFromTagRequest.Unmarshal(m, b)
}
func (m *EditFileFromTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditFileFromTagRequest.Marshal(b, m, deterministic)
}
func (m *EditFileFromTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditFileFromTagRequest.Merge(m, src)
}
func (m *EditFileFromTagRequest) XXX_Size() int {
	return xxx_messageInfo_EditFileFromTagRequest.Size(m)
}
func (m *EditFileFromTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditFileFromTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditFileFromTagRequest proto.InternalMessageInfo

func (m *EditFileFromTagRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *EditFileFromTagRequest) GetMod() *TagEncoder {
	if m != nil {
		return m.Mod
	}
	return nil
}

type EditFileFromTagResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditFileFromTagResponse) Reset()         { *m = EditFileFromTagResponse{} }
func (m *EditFileFromTagResponse) String() string { return proto.CompactTextString(m) }
func (*EditFileFromTagResponse) ProtoMessage()    {}
func (*EditFileFromTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{26}
}

func (m *EditFileFromTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditFileFromTagResponse.Unmarshal(m, b)
}
func (m *EditFileFromTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditFileFromTagResponse.Marshal(b, m, deterministic)
}
func (m *EditFileFromTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditFileFromTagResponse.Merge(m, src)
}
func (m *EditFileFromTagResponse) XXX_Size() int {
	return xxx_messageInfo_EditFileFromTagResponse.Size(m)
}
func (m *EditFileFromTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditFileFromTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditFileFromTagResponse proto.InternalMessageInfo

type AddFileRequest struct {
	File                 *TagFile `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Replica              bool     `protobuf:"varint,2,opt,name=Replica,proto3" json:"Replica,omitempty"`
	Lock                 bool     `protobuf:"varint,3,opt,name=Lock,proto3" json:"Lock,omitempty"`
	IP                   string   `protobuf:"bytes,4,opt,name=IP,proto3" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFileRequest) Reset()         { *m = AddFileRequest{} }
func (m *AddFileRequest) String() string { return proto.CompactTextString(m) }
func (*AddFileRequest) ProtoMessage()    {}
func (*AddFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{27}
}

func (m *AddFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFileRequest.Unmarshal(m, b)
}
func (m *AddFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFileRequest.Marshal(b, m, deterministic)
}
func (m *AddFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFileRequest.Merge(m, src)
}
func (m *AddFileRequest) XXX_Size() int {
	return xxx_messageInfo_AddFileRequest.Size(m)
}
func (m *AddFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFileRequest proto.InternalMessageInfo

func (m *AddFileRequest) GetFile() *TagFile {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *AddFileRequest) GetReplica() bool {
	if m != nil {
		return m.Replica
	}
	return false
}

func (m *AddFileRequest) GetLock() bool {
	if m != nil {
		return m.Lock
	}
	return false
}

func (m *AddFileRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

type AddFileResponse struct {
	Destine              *Node    `protobuf:"bytes,1,opt,name=destine,proto3" json:"destine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFileResponse) Reset()         { *m = AddFileResponse{} }
func (m *AddFileResponse) String() string { return proto.CompactTextString(m) }
func (*AddFileResponse) ProtoMessage()    {}
func (*AddFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{28}
}

func (m *AddFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFileResponse.Unmarshal(m, b)
}
func (m *AddFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFileResponse.Marshal(b, m, deterministic)
}
func (m *AddFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFileResponse.Merge(m, src)
}
func (m *AddFileResponse) XXX_Size() int {
	return xxx_messageInfo_AddFileResponse.Size(m)
}
func (m *AddFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFileResponse proto.InternalMessageInfo

func (m *AddFileResponse) GetDestine() *Node {
	if m != nil {
		return m.Destine
	}
	return nil
}

type AddTagRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=FileName,proto3" json:"FileName,omitempty"`
	ExtensioName         string   `protobuf:"bytes,3,opt,name=ExtensioName,proto3" json:"ExtensioName,omitempty"`
	TargetNode           *Node    `protobuf:"bytes,4,opt,name=TargetNode,proto3" json:"TargetNode,omitempty"`
	Replica              bool     `protobuf:"varint,5,opt,name=Replica,proto3" json:"Replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagRequest) Reset()         { *m = AddTagRequest{} }
func (m *AddTagRequest) String() string { return proto.CompactTextString(m) }
func (*AddTagRequest) ProtoMessage()    {}
func (*AddTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{29}
}

func (m *AddTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagRequest.Unmarshal(m, b)
}
func (m *AddTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagRequest.Marshal(b, m, deterministic)
}
func (m *AddTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagRequest.Merge(m, src)
}
func (m *AddTagRequest) XXX_Size() int {
	return xxx_messageInfo_AddTagRequest.Size(m)
}
func (m *AddTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagRequest proto.InternalMessageInfo

func (m *AddTagRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *AddTagRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *AddTagRequest) GetExtensioName() string {
	if m != nil {
		return m.ExtensioName
	}
	return ""
}

func (m *AddTagRequest) GetTargetNode() *Node {
	if m != nil {
		return m.TargetNode
	}
	return nil
}

func (m *AddTagRequest) GetReplica() bool {
	if m != nil {
		return m.Replica
	}
	return false
}

type AddTagResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagResponse) Reset()         { *m = AddTagResponse{} }
func (m *AddTagResponse) String() string { return proto.CompactTextString(m) }
func (*AddTagResponse) ProtoMessage()    {}
func (*AddTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{30}
}

func (m *AddTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagResponse.Unmarshal(m, b)
}
func (m *AddTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagResponse.Marshal(b, m, deterministic)
}
func (m *AddTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagResponse.Merge(m, src)
}
func (m *AddTagResponse) XXX_Size() int {
	return xxx_messageInfo_AddTagResponse.Size(m)
}
func (m *AddTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagResponse proto.InternalMessageInfo

type DeleteFileRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileExtension        string   `protobuf:"bytes,2,opt,name=FileExtension,proto3" json:"FileExtension,omitempty"`
	Replica              bool     `protobuf:"varint,3,opt,name=Replica,proto3" json:"Replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{31}
}

func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(m, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *DeleteFileRequest) GetFileExtension() string {
	if m != nil {
		return m.FileExtension
	}
	return ""
}

func (m *DeleteFileRequest) GetReplica() bool {
	if m != nil {
		return m.Replica
	}
	return false
}

type DeleteFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{32}
}

func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(m, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

type DeleteFileFromTagRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileExtension        string   `protobuf:"bytes,3,opt,name=FileExtension,proto3" json:"FileExtension,omitempty"`
	Replica              bool     `protobuf:"varint,4,opt,name=Replica,proto3" json:"Replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileFromTagRequest) Reset()         { *m = DeleteFileFromTagRequest{} }
func (m *DeleteFileFromTagRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileFromTagRequest) ProtoMessage()    {}
func (*DeleteFileFromTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{33}
}

func (m *DeleteFileFromTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileFromTagRequest.Unmarshal(m, b)
}
func (m *DeleteFileFromTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileFromTagRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFileFromTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileFromTagRequest.Merge(m, src)
}
func (m *DeleteFileFromTagRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileFromTagRequest.Size(m)
}
func (m *DeleteFileFromTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileFromTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileFromTagRequest proto.InternalMessageInfo

func (m *DeleteFileFromTagRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *DeleteFileFromTagRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *DeleteFileFromTagRequest) GetFileExtension() string {
	if m != nil {
		return m.FileExtension
	}
	return ""
}

func (m *DeleteFileFromTagRequest) GetReplica() bool {
	if m != nil {
		return m.Replica
	}
	return false
}

type DeleteFileFromTagResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileFromTagResponse) Reset()         { *m = DeleteFileFromTagResponse{} }
func (m *DeleteFileFromTagResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileFromTagResponse) ProtoMessage()    {}
func (*DeleteFileFromTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{34}
}

func (m *DeleteFileFromTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileFromTagResponse.Unmarshal(m, b)
}
func (m *DeleteFileFromTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileFromTagResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFileFromTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileFromTagResponse.Merge(m, src)
}
func (m *DeleteFileFromTagResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileFromTagResponse.Size(m)
}
func (m *DeleteFileFromTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileFromTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileFromTagResponse proto.InternalMessageInfo

type DeleteTagRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Replica              bool     `protobuf:"varint,2,opt,name=Replica,proto3" json:"Replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagRequest) Reset()         { *m = DeleteTagRequest{} }
func (m *DeleteTagRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTagRequest) ProtoMessage()    {}
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{35}
}

func (m *DeleteTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagRequest.Unmarshal(m, b)
}
func (m *DeleteTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagRequest.Merge(m, src)
}
func (m *DeleteTagRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTagRequest.Size(m)
}
func (m *DeleteTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagRequest proto.InternalMessageInfo

func (m *DeleteTagRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *DeleteTagRequest) GetReplica() bool {
	if m != nil {
		return m.Replica
	}
	return false
}

type DeleteTagResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagResponse) Reset()         { *m = DeleteTagResponse{} }
func (m *DeleteTagResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTagResponse) ProtoMessage()    {}
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{36}
}

func (m *DeleteTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagResponse.Unmarshal(m, b)
}
func (m *DeleteTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagResponse.Merge(m, src)
}
func (m *DeleteTagResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTagResponse.Size(m)
}
func (m *DeleteTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagResponse proto.InternalMessageInfo

type GetTagRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagRequest) Reset()         { *m = GetTagRequest{} }
func (m *GetTagRequest) String() string { return proto.CompactTextString(m) }
func (*GetTagRequest) ProtoMessage()    {}
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{37}
}

func (m *GetTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagRequest.Unmarshal(m, b)
}
func (m *GetTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagRequest.Marshal(b, m, deterministic)
}
func (m *GetTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagRequest.Merge(m, src)
}
func (m *GetTagRequest) XXX_Size() int {
	return xxx_messageInfo_GetTagRequest.Size(m)
}
func (m *GetTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagRequest proto.InternalMessageInfo

func (m *GetTagRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type GetTagResponse struct {
	Encoder              *TagEncoder `protobuf:"bytes,1,opt,name=Encoder,proto3" json:"Encoder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetTagResponse) Reset()         { *m = GetTagResponse{} }
func (m *GetTagResponse) String() string { return proto.CompactTextString(m) }
func (*GetTagResponse) ProtoMessage()    {}
func (*GetTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{38}
}

func (m *GetTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagResponse.Unmarshal(m, b)
}
func (m *GetTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagResponse.Marshal(b, m, deterministic)
}
func (m *GetTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagResponse.Merge(m, src)
}
func (m *GetTagResponse) XXX_Size() int {
	return xxx_messageInfo_GetTagResponse.Size(m)
}
func (m *GetTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagResponse proto.InternalMessageInfo

func (m *GetTagResponse) GetEncoder() *TagEncoder {
	if m != nil {
		return m.Encoder
	}
	return nil
}

type DeleteFileByQueryRequest struct {
	Tag                  []string `protobuf:"bytes,1,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileByQueryRequest) Reset()         { *m = DeleteFileByQueryRequest{} }
func (m *DeleteFileByQueryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileByQueryRequest) ProtoMessage()    {}
func (*DeleteFileByQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{39}
}

func (m *DeleteFileByQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileByQueryRequest.Unmarshal(m, b)
}
func (m *DeleteFileByQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileByQueryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFileByQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileByQueryRequest.Merge(m, src)
}
func (m *DeleteFileByQueryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileByQueryRequest.Size(m)
}
func (m *DeleteFileByQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileByQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileByQueryRequest proto.InternalMessageInfo

func (m *DeleteFileByQueryRequest) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type DeleteFileByQueryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileByQueryResponse) Reset()         { *m = DeleteFileByQueryResponse{} }
func (m *DeleteFileByQueryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileByQueryResponse) ProtoMessage()    {}
func (*DeleteFileByQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{40}
}

func (m *DeleteFileByQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileByQueryResponse.Unmarshal(m, b)
}
func (m *DeleteFileByQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileByQueryResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFileByQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileByQueryResponse.Merge(m, src)
}
func (m *DeleteFileByQueryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileByQueryResponse.Size(m)
}
func (m *DeleteFileByQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileByQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileByQueryResponse proto.InternalMessageInfo

type ListByQueryRequest struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListByQueryRequest) Reset()         { *m = ListByQueryRequest{} }
func (m *ListByQueryRequest) String() string { return proto.CompactTextString(m) }
func (*ListByQueryRequest) ProtoMessage()    {}
func (*ListByQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{41}
}

func (m *ListByQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListByQueryRequest.Unmarshal(m, b)
}
func (m *ListByQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListByQueryRequest.Marshal(b, m, deterministic)
}
func (m *ListByQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListByQueryRequest.Merge(m, src)
}
func (m *ListByQueryRequest) XXX_Size() int {
	return xxx_messageInfo_ListByQueryRequest.Size(m)
}
func (m *ListByQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListByQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListByQueryRequest proto.InternalMessageInfo

func (m *ListByQueryRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ListByQueryResponse struct {
	Response             map[string][]byte `protobuf:"bytes,1,rep,name=Response,proto3" json:"Response,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListByQueryResponse) Reset()         { *m = ListByQueryResponse{} }
func (m *ListByQueryResponse) String() string { return proto.CompactTextString(m) }
func (*ListByQueryResponse) ProtoMessage()    {}
func (*ListByQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{42}
}

func (m *ListByQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListByQueryResponse.Unmarshal(m, b)
}
func (m *ListByQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListByQueryResponse.Marshal(b, m, deterministic)
}
func (m *ListByQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListByQueryResponse.Merge(m, src)
}
func (m *ListByQueryResponse) XXX_Size() int {
	return xxx_messageInfo_ListByQueryResponse.Size(m)
}
func (m *ListByQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListByQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListByQueryResponse proto.InternalMessageInfo

func (m *ListByQueryResponse) GetResponse() map[string][]byte {
	if m != nil {
		return m.Response
	}
	return nil
}

type GetFileInfoRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileExtension        string   `protobuf:"bytes,2,opt,name=FileExtension,proto3" json:"FileExtension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileInfoRequest) Reset()         { *m = GetFileInfoRequest{} }
func (m *GetFileInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileInfoRequest) ProtoMessage()    {}
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{43}
}

func (m *GetFileInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileInfoRequest.Unmarshal(m, b)
}
func (m *GetFileInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetFileInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileInfoRequest.Merge(m, src)
}
func (m *GetFileInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileInfoRequest.Size(m)
}
func (m *GetFileInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileInfoRequest proto.InternalMessageInfo

func (m *GetFileInfoRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *GetFileInfoRequest) GetFileExtension() string {
	if m != nil {
		return m.FileExtension
	}
	return ""
}

type GetFileInfoResponse struct {
	Info                 []byte   `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileInfoResponse) Reset()         { *m = GetFileInfoResponse{} }
func (m *GetFileInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileInfoResponse) ProtoMessage()    {}
func (*GetFileInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{44}
}

func (m *GetFileInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileInfoResponse.Unmarshal(m, b)
}
func (m *GetFileInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetFileInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileInfoResponse.Merge(m, src)
}
func (m *GetFileInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileInfoResponse.Size(m)
}
func (m *GetFileInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileInfoResponse proto.InternalMessageInfo

func (m *GetFileInfoResponse) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

type DeleteTagsByQueryRequest struct {
	QueryTags            []string `protobuf:"bytes,1,rep,name=QueryTags,proto3" json:"QueryTags,omitempty"`
	RemoveTags           []string `protobuf:"bytes,2,rep,name=RemoveTags,proto3" json:"RemoveTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagsByQueryRequest) Reset()         { *m = DeleteTagsByQueryRequest{} }
func (m *DeleteTagsByQueryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTagsByQueryRequest) ProtoMessage()    {}
func (*DeleteTagsByQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{45}
}

func (m *DeleteTagsByQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagsByQueryRequest.Unmarshal(m, b)
}
func (m *DeleteTagsByQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagsByQueryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTagsByQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagsByQueryRequest.Merge(m, src)
}
func (m *DeleteTagsByQueryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTagsByQueryRequest.Size(m)
}
func (m *DeleteTagsByQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagsByQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagsByQueryRequest proto.InternalMessageInfo

func (m *DeleteTagsByQueryRequest) GetQueryTags() []string {
	if m != nil {
		return m.QueryTags
	}
	return nil
}

func (m *DeleteTagsByQueryRequest) GetRemoveTags() []string {
	if m != nil {
		return m.RemoveTags
	}
	return nil
}

type DeleteTagsByQueryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagsByQueryResponse) Reset()         { *m = DeleteTagsByQueryResponse{} }
func (m *DeleteTagsByQueryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTagsByQueryResponse) ProtoMessage()    {}
func (*DeleteTagsByQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{46}
}

func (m *DeleteTagsByQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagsByQueryResponse.Unmarshal(m, b)
}
func (m *DeleteTagsByQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagsByQueryResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTagsByQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagsByQueryResponse.Merge(m, src)
}
func (m *DeleteTagsByQueryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTagsByQueryResponse.Size(m)
}
func (m *DeleteTagsByQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagsByQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagsByQueryResponse proto.InternalMessageInfo

type AddTagsByQueryRequest struct {
	QueryTags            []string `protobuf:"bytes,1,rep,name=QueryTags,proto3" json:"QueryTags,omitempty"`
	AddTags              []string `protobuf:"bytes,2,rep,name=AddTags,proto3" json:"AddTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagsByQueryRequest) Reset()         { *m = AddTagsByQueryRequest{} }
func (m *AddTagsByQueryRequest) String() string { return proto.CompactTextString(m) }
func (*AddTagsByQueryRequest) ProtoMessage()    {}
func (*AddTagsByQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{47}
}

func (m *AddTagsByQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagsByQueryRequest.Unmarshal(m, b)
}
func (m *AddTagsByQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagsByQueryRequest.Marshal(b, m, deterministic)
}
func (m *AddTagsByQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagsByQueryRequest.Merge(m, src)
}
func (m *AddTagsByQueryRequest) XXX_Size() int {
	return xxx_messageInfo_AddTagsByQueryRequest.Size(m)
}
func (m *AddTagsByQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagsByQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagsByQueryRequest proto.InternalMessageInfo

func (m *AddTagsByQueryRequest) GetQueryTags() []string {
	if m != nil {
		return m.QueryTags
	}
	return nil
}

func (m *AddTagsByQueryRequest) GetAddTags() []string {
	if m != nil {
		return m.AddTags
	}
	return nil
}

type AddTagsByQueryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagsByQueryResponse) Reset()         { *m = AddTagsByQueryResponse{} }
func (m *AddTagsByQueryResponse) String() string { return proto.CompactTextString(m) }
func (*AddTagsByQueryResponse) ProtoMessage()    {}
func (*AddTagsByQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{48}
}

func (m *AddTagsByQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagsByQueryResponse.Unmarshal(m, b)
}
func (m *AddTagsByQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagsByQueryResponse.Marshal(b, m, deterministic)
}
func (m *AddTagsByQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagsByQueryResponse.Merge(m, src)
}
func (m *AddTagsByQueryResponse) XXX_Size() int {
	return xxx_messageInfo_AddTagsByQueryResponse.Size(m)
}
func (m *AddTagsByQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagsByQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagsByQueryResponse proto.InternalMessageInfo

type AddTagsToFileRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileExtension        string   `protobuf:"bytes,2,opt,name=FileExtension,proto3" json:"FileExtension,omitempty"`
	ListTags             []string `protobuf:"bytes,3,rep,name=ListTags,proto3" json:"ListTags,omitempty"`
	Replica              bool     `protobuf:"varint,4,opt,name=Replica,proto3" json:"Replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagsToFileRequest) Reset()         { *m = AddTagsToFileRequest{} }
func (m *AddTagsToFileRequest) String() string { return proto.CompactTextString(m) }
func (*AddTagsToFileRequest) ProtoMessage()    {}
func (*AddTagsToFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{49}
}

func (m *AddTagsToFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagsToFileRequest.Unmarshal(m, b)
}
func (m *AddTagsToFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagsToFileRequest.Marshal(b, m, deterministic)
}
func (m *AddTagsToFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagsToFileRequest.Merge(m, src)
}
func (m *AddTagsToFileRequest) XXX_Size() int {
	return xxx_messageInfo_AddTagsToFileRequest.Size(m)
}
func (m *AddTagsToFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagsToFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagsToFileRequest proto.InternalMessageInfo

func (m *AddTagsToFileRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *AddTagsToFileRequest) GetFileExtension() string {
	if m != nil {
		return m.FileExtension
	}
	return ""
}

func (m *AddTagsToFileRequest) GetListTags() []string {
	if m != nil {
		return m.ListTags
	}
	return nil
}

func (m *AddTagsToFileRequest) GetReplica() bool {
	if m != nil {
		return m.Replica
	}
	return false
}

type AddTagsToFileResponse struct {
	Destiny              *Node    `protobuf:"bytes,1,opt,name=Destiny,proto3" json:"Destiny,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagsToFileResponse) Reset()         { *m = AddTagsToFileResponse{} }
func (m *AddTagsToFileResponse) String() string { return proto.CompactTextString(m) }
func (*AddTagsToFileResponse) ProtoMessage()    {}
func (*AddTagsToFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{50}
}

func (m *AddTagsToFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagsToFileResponse.Unmarshal(m, b)
}
func (m *AddTagsToFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagsToFileResponse.Marshal(b, m, deterministic)
}
func (m *AddTagsToFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagsToFileResponse.Merge(m, src)
}
func (m *AddTagsToFileResponse) XXX_Size() int {
	return xxx_messageInfo_AddTagsToFileResponse.Size(m)
}
func (m *AddTagsToFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagsToFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagsToFileResponse proto.InternalMessageInfo

func (m *AddTagsToFileResponse) GetDestiny() *Node {
	if m != nil {
		return m.Destiny
	}
	return nil
}

type DeleteTagsFromFileRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileExtension        string   `protobuf:"bytes,2,opt,name=FileExtension,proto3" json:"FileExtension,omitempty"`
	ListTags             []string `protobuf:"bytes,3,rep,name=ListTags,proto3" json:"ListTags,omitempty"`
	Replica              bool     `protobuf:"varint,4,opt,name=Replica,proto3" json:"Replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagsFromFileRequest) Reset()         { *m = DeleteTagsFromFileRequest{} }
func (m *DeleteTagsFromFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTagsFromFileRequest) ProtoMessage()    {}
func (*DeleteTagsFromFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{51}
}

func (m *DeleteTagsFromFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagsFromFileRequest.Unmarshal(m, b)
}
func (m *DeleteTagsFromFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagsFromFileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTagsFromFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagsFromFileRequest.Merge(m, src)
}
func (m *DeleteTagsFromFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTagsFromFileRequest.Size(m)
}
func (m *DeleteTagsFromFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagsFromFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagsFromFileRequest proto.InternalMessageInfo

func (m *DeleteTagsFromFileRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *DeleteTagsFromFileRequest) GetFileExtension() string {
	if m != nil {
		return m.FileExtension
	}
	return ""
}

func (m *DeleteTagsFromFileRequest) GetListTags() []string {
	if m != nil {
		return m.ListTags
	}
	return nil
}

func (m *DeleteTagsFromFileRequest) GetReplica() bool {
	if m != nil {
		return m.Replica
	}
	return false
}

type DeleteTagsFromFileResponse struct {
	Destiny              *Node    `protobuf:"bytes,1,opt,name=Destiny,proto3" json:"Destiny,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagsFromFileResponse) Reset()         { *m = DeleteTagsFromFileResponse{} }
func (m *DeleteTagsFromFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTagsFromFileResponse) ProtoMessage()    {}
func (*DeleteTagsFromFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a7ffd2fbed58b2, []int{52}
}

func (m *DeleteTagsFromFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagsFromFileResponse.Unmarshal(m, b)
}
func (m *DeleteTagsFromFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagsFromFileResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTagsFromFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagsFromFileResponse.Merge(m, src)
}
func (m *DeleteTagsFromFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTagsFromFileResponse.Size(m)
}
func (m *DeleteTagsFromFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagsFromFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagsFromFileResponse proto.InternalMessageInfo

func (m *DeleteTagsFromFileResponse) GetDestiny() *Node {
	if m != nil {
		return m.Destiny
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "chord.Node")
	proto.RegisterType((*TagFile)(nil), "chord.TagFile")
	proto.RegisterType((*TagEncoder)(nil), "chord.TagEncoder")
	proto.RegisterType((*GetPredecessorRequest)(nil), "chord.GetPredecessorRequest")
	proto.RegisterType((*GetSuccessorRequest)(nil), "chord.GetSuccessorRequest")
	proto.RegisterType((*CheckRequest)(nil), "chord.CheckRequest")
	proto.RegisterType((*PartitionRequest)(nil), "chord.PartitionRequest")
	proto.RegisterType((*ExtendResponse)(nil), "chord.ExtendResponse")
	proto.RegisterType((*SetPredecessorResponse)(nil), "chord.SetPredecessorResponse")
	proto.RegisterType((*SetSuccessorResponse)(nil), "chord.SetSuccessorResponse")
	proto.RegisterType((*NotifyResponse)(nil), "chord.NotifyResponse")
	proto.RegisterType((*CheckResponse)(nil), "chord.CheckResponse")
	proto.RegisterType((*SetResponse)(nil), "chord.SetResponse")
	proto.RegisterType((*DeleteResponse)(nil), "chord.DeleteResponse")
	proto.RegisterType((*DiscardResponse)(nil), "chord.DiscardResponse")
	proto.RegisterType((*SetPredecessorRequest)(nil), "chord.SetPredecessorRequest")
	proto.RegisterType((*SetSuccessorRequest)(nil), "chord.SetSuccessorRequest")
	proto.RegisterType((*NotifyRequest)(nil), "chord.NotifyRequest")
	proto.RegisterType((*GetPredecessorResponse)(nil), "chord.GetPredecessorResponse")
	proto.RegisterType((*GetSuccessorResponse)(nil), "chord.GetSuccessorResponse")
	proto.RegisterType((*FindSuccesorResponse)(nil), "chord.FindSuccesorResponse")
	proto.RegisterType((*FindSuccesorRequest)(nil), "chord.FindSuccesorRequest")
	proto.RegisterType((*ExtendRequest)(nil), "chord.ExtendRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "chord.ExtendRequest.TagsEntry")
	proto.RegisterType((*DiscardRequest)(nil), "chord.DiscardRequest")
	proto.RegisterType((*PartitionResponse)(nil), "chord.PartitionResponse")
	proto.RegisterMapType((map[string][]byte)(nil), "chord.PartitionResponse.InTagsEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "chord.PartitionResponse.OutTagsEntry")
	proto.RegisterType((*EditFileFromTagRequest)(nil), "chord.EditFileFromTagRequest")
	proto.RegisterType((*EditFileFromTagResponse)(nil), "chord.EditFileFromTagResponse")
	proto.RegisterType((*AddFileRequest)(nil), "chord.AddFileRequest")
	proto.RegisterType((*AddFileResponse)(nil), "chord.AddFileResponse")
	proto.RegisterType((*AddTagRequest)(nil), "chord.AddTagRequest")
	proto.RegisterType((*AddTagResponse)(nil), "chord.AddTagResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "chord.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "chord.DeleteFileResponse")
	proto.RegisterType((*DeleteFileFromTagRequest)(nil), "chord.DeleteFileFromTagRequest")
	proto.RegisterType((*DeleteFileFromTagResponse)(nil), "chord.DeleteFileFromTagResponse")
	proto.RegisterType((*DeleteTagRequest)(nil), "chord.DeleteTagRequest")
	proto.RegisterType((*DeleteTagResponse)(nil), "chord.DeleteTagResponse")
	proto.RegisterType((*GetTagRequest)(nil), "chord.GetTagRequest")
	proto.RegisterType((*GetTagResponse)(nil), "chord.GetTagResponse")
	proto.RegisterType((*DeleteFileByQueryRequest)(nil), "chord.DeleteFileByQueryRequest")
	proto.RegisterType((*DeleteFileByQueryResponse)(nil), "chord.DeleteFileByQueryResponse")
	proto.RegisterType((*ListByQueryRequest)(nil), "chord.ListByQueryRequest")
	proto.RegisterType((*ListByQueryResponse)(nil), "chord.ListByQueryResponse")
	proto.RegisterMapType((map[string][]byte)(nil), "chord.ListByQueryResponse.ResponseEntry")
	proto.RegisterType((*GetFileInfoRequest)(nil), "chord.GetFileInfoRequest")
	proto.RegisterType((*GetFileInfoResponse)(nil), "chord.GetFileInfoResponse")
	proto.RegisterType((*DeleteTagsByQueryRequest)(nil), "chord.DeleteTagsByQueryRequest")
	proto.RegisterType((*DeleteTagsByQueryResponse)(nil), "chord.DeleteTagsByQueryResponse")
	proto.RegisterType((*AddTagsByQueryRequest)(nil), "chord.AddTagsByQueryRequest")
	proto.RegisterType((*AddTagsByQueryResponse)(nil), "chord.AddTagsByQueryResponse")
	proto.RegisterType((*AddTagsToFileRequest)(nil), "chord.AddTagsToFileRequest")
	proto.RegisterType((*AddTagsToFileResponse)(nil), "chord.AddTagsToFileResponse")
	proto.RegisterType((*DeleteTagsFromFileRequest)(nil), "chord.DeleteTagsFromFileRequest")
	proto.RegisterType((*DeleteTagsFromFileResponse)(nil), "chord.DeleteTagsFromFileResponse")
}

func init() {
	proto.RegisterFile("server/proto/chord.proto", fileDescriptor_e1a7ffd2fbed58b2)
}

var fileDescriptor_e1a7ffd2fbed58b2 = []byte{
	// 1504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcd, 0x72, 0x1b, 0xc5,
	0x13, 0xaf, 0x95, 0x64, 0xcb, 0x6a, 0x7d, 0xd8, 0x1e, 0xcb, 0xce, 0x7a, 0xe3, 0x7f, 0xfe, 0xce,
	0x26, 0x29, 0x1c, 0x02, 0x0e, 0x25, 0xa0, 0x12, 0x0c, 0x24, 0x71, 0x22, 0x5b, 0x88, 0x4a, 0x62,
	0xb1, 0x52, 0xa5, 0x80, 0x9b, 0x90, 0x26, 0x8a, 0xca, 0x8e, 0xd6, 0xec, 0xae, 0x53, 0xf8, 0x0d,
	0x38, 0x71, 0xe1, 0x42, 0x71, 0xcc, 0x89, 0xb7, 0xe2, 0x55, 0xa8, 0x99, 0xe9, 0x99, 0x9d, 0x59,
	0x8d, 0x94, 0x52, 0x91, 0x03, 0xb7, 0x99, 0xfe, 0xfc, 0x4d, 0x6f, 0x4f, 0x77, 0xcf, 0x82, 0x1b,
	0xd3, 0xe8, 0x0d, 0x8d, 0xee, 0x9e, 0x47, 0x61, 0x12, 0xde, 0x1d, 0xbc, 0x0a, 0xa3, 0xe1, 0x3e,
	0x5f, 0x93, 0x25, 0xbe, 0xf1, 0x0f, 0xa0, 0xf0, 0x3c, 0x1c, 0x52, 0x52, 0x83, 0x5c, 0xbb, 0xe9,
	0x3a, 0xbb, 0xce, 0x5e, 0x25, 0xc8, 0xb5, 0x9b, 0x7c, 0xdf, 0x71, 0x73, 0xbb, 0xce, 0x5e, 0x29,
	0xc8, 0xb5, 0x3b, 0x84, 0x40, 0xe1, 0x3c, 0x8c, 0x12, 0x37, 0xcf, 0x29, 0x7c, 0xed, 0x0f, 0xa0,
	0xd8, 0xeb, 0x8f, 0x8e, 0xc7, 0x67, 0x94, 0xb1, 0x27, 0xfd, 0xd7, 0x94, 0x1b, 0x28, 0x05, 0x7c,
	0x4d, 0x76, 0xa0, 0x44, 0x7f, 0x49, 0xe8, 0x24, 0x1e, 0x87, 0x13, 0xb4, 0x94, 0x12, 0x98, 0xc6,
	0xcb, 0xf1, 0x19, 0xe5, 0x06, 0x2b, 0x01, 0x5f, 0x33, 0x5a, 0xd2, 0x1f, 0xc5, 0x6e, 0x61, 0x37,
	0xcf, 0xac, 0xb0, 0xb5, 0xff, 0xa7, 0x03, 0xd0, 0xeb, 0x8f, 0x8e, 0x26, 0x83, 0x70, 0x48, 0x23,
	0xe2, 0xc1, 0x0a, 0x73, 0xf8, 0x3c, 0x75, 0xa6, 0xf6, 0xe4, 0x26, 0x54, 0xd9, 0xfa, 0x28, 0xe3,
	0xd4, 0x24, 0x92, 0x2d, 0x58, 0x66, 0x27, 0x6e, 0x37, 0xd1, 0x35, 0xee, 0x14, 0xbd, 0xe3, 0x16,
	0xb8, 0x1a, 0xee, 0x98, 0x47, 0xb6, 0xea, 0xb0, 0xd3, 0x2f, 0x09, 0x8f, 0x72, 0xef, 0x5f, 0x81,
	0xcd, 0x16, 0x4d, 0x3a, 0x11, 0x1d, 0xd2, 0x01, 0x8d, 0xe3, 0x30, 0x0a, 0xe8, 0xcf, 0x17, 0x34,
	0x4e, 0xfc, 0x4d, 0xd8, 0x68, 0xd1, 0xa4, 0x7b, 0x31, 0x30, 0xc9, 0x35, 0xa8, 0x3c, 0x79, 0x45,
	0x07, 0xa7, 0x72, 0x4f, 0x60, 0xad, 0xd3, 0x8f, 0x92, 0x71, 0x32, 0x0e, 0x27, 0x92, 0xb6, 0x06,
	0x35, 0x0e, 0x76, 0x18, 0xd0, 0xf8, 0x3c, 0x9c, 0xc4, 0xd4, 0x77, 0x61, 0xab, 0x9b, 0xf1, 0x82,
	0x9c, 0x2d, 0xa8, 0x77, 0x0d, 0x37, 0x48, 0x5f, 0x83, 0xda, 0xf3, 0x30, 0x19, 0xbf, 0xbc, 0x54,
	0x94, 0x55, 0xa8, 0xa2, 0x67, 0x24, 0x54, 0xa1, 0xdc, 0xa5, 0x89, 0xae, 0xd1, 0xa4, 0x67, 0x34,
	0xa1, 0x8a, 0xb2, 0x0e, 0xab, 0xcd, 0x71, 0x3c, 0xe8, 0x47, 0x29, 0x90, 0x63, 0xd8, 0xec, 0xda,
	0x8e, 0x4b, 0x3e, 0x86, 0xf2, 0x79, 0x4a, 0xe5, 0x1f, 0xa6, 0xdc, 0x28, 0xef, 0x8b, 0x7c, 0x63,
	0xd1, 0x0a, 0x74, 0xbe, 0xff, 0x08, 0x36, 0xba, 0xd3, 0xd1, 0x21, 0xb7, 0xa1, 0x14, 0x4b, 0x9a,
	0xcd, 0x46, 0xca, 0xf5, 0x3f, 0x83, 0xaa, 0x3c, 0xa0, 0xd0, 0xbd, 0x01, 0xcb, 0x13, 0x4e, 0xb0,
	0x29, 0x22, 0xcb, 0x6f, 0xc1, 0x56, 0xcb, 0x1a, 0xc8, 0x45, 0x0f, 0x70, 0x08, 0xf5, 0x96, 0x25,
	0xee, 0x8b, 0x9c, 0xe0, 0x21, 0xd4, 0x8f, 0xc7, 0x93, 0xa1, 0xb0, 0xa1, 0x99, 0xf8, 0x00, 0x56,
	0x62, 0xa4, 0xd9, 0x2c, 0x28, 0xa6, 0x7f, 0x0b, 0x36, 0x4c, 0x03, 0x22, 0x10, 0x99, 0x8b, 0xec,
	0xbf, 0x75, 0xa0, 0x2a, 0xf3, 0x49, 0x48, 0xdc, 0x84, 0x25, 0x76, 0x23, 0x62, 0xd7, 0xd9, 0xcd,
	0xef, 0x95, 0x1b, 0x35, 0x34, 0x8f, 0x57, 0x39, 0x10, 0x4c, 0xd2, 0x80, 0x42, 0x8f, 0xdd, 0xc5,
	0x1c, 0x17, 0xba, 0x86, 0x42, 0x86, 0x25, 0xa6, 0x12, 0x1f, 0x4d, 0x92, 0xe8, 0x32, 0xe0, 0xb2,
	0xde, 0x3d, 0x28, 0x29, 0x12, 0x59, 0x83, 0xfc, 0x29, 0xbd, 0xc4, 0x4b, 0xca, 0x96, 0xa4, 0x0e,
	0x4b, 0x6f, 0xfa, 0x67, 0x17, 0x94, 0xdf, 0xcb, 0x4a, 0x20, 0x36, 0x07, 0xb9, 0xfb, 0x8e, 0x7f,
	0x00, 0x35, 0x95, 0x6b, 0x02, 0x24, 0x41, 0xf7, 0x8e, 0x28, 0x05, 0x6c, 0xcd, 0xf4, 0x05, 0xf0,
	0x1c, 0x27, 0x8a, 0x8d, 0xff, 0x77, 0x0e, 0xd6, 0xb5, 0x4b, 0x84, 0x61, 0xdc, 0x83, 0x62, 0x7b,
	0x32, 0xef, 0x98, 0x92, 0x4d, 0x3e, 0x84, 0x95, 0x93, 0x8b, 0x24, 0x35, 0x3c, 0x2d, 0xaa, 0xf8,
	0xe4, 0x2b, 0x58, 0x6e, 0x4f, 0x38, 0xae, 0x3c, 0x97, 0xbc, 0x89, 0x92, 0x53, 0xfe, 0xf7, 0x85,
	0x98, 0x08, 0x0e, 0xea, 0x90, 0x87, 0x50, 0x3c, 0xb9, 0x48, 0x7a, 0xb2, 0xc2, 0x95, 0x1b, 0xb7,
	0x66, 0xaa, 0xa3, 0x9c, 0xd0, 0x97, 0x5a, 0xde, 0x17, 0x50, 0xd6, 0xec, 0x2e, 0x12, 0x61, 0xef,
	0x00, 0x2a, 0xba, 0xcd, 0x85, 0xbe, 0xce, 0x09, 0x6c, 0x1d, 0x0d, 0xc7, 0x3c, 0x04, 0xc7, 0x51,
	0xf8, 0xba, 0xd7, 0x1f, 0xc9, 0xaf, 0xb4, 0x06, 0xf9, 0x5e, 0x7f, 0x24, 0xad, 0xf4, 0xfa, 0x23,
	0x72, 0x03, 0xf2, 0xcf, 0xc2, 0x21, 0xb7, 0x51, 0x6e, 0xac, 0xa7, 0x81, 0xc4, 0xfa, 0x1d, 0x30,
	0xae, 0xbf, 0x0d, 0x57, 0xa6, 0x0c, 0x62, 0x89, 0x89, 0xa0, 0x76, 0x38, 0x1c, 0xf2, 0xb0, 0xa3,
	0x0f, 0x1f, 0x1b, 0x85, 0xb8, 0x0c, 0xd9, 0x6f, 0x23, 0x1a, 0x87, 0x0b, 0xc5, 0x80, 0x9e, 0x9f,
	0x8d, 0x07, 0x7d, 0xee, 0x79, 0x25, 0x90, 0x5b, 0x96, 0x47, 0x4f, 0xc3, 0xc1, 0x29, 0xaf, 0xf5,
	0x2b, 0x01, 0x5f, 0x63, 0x6f, 0x2b, 0xc8, 0xde, 0xe6, 0xdf, 0x87, 0x55, 0xe5, 0x13, 0xd3, 0xe7,
	0x16, 0x14, 0x87, 0x34, 0x4e, 0xc6, 0x13, 0x6a, 0xbb, 0x84, 0x92, 0xe7, 0xff, 0xe5, 0x40, 0xf5,
	0x70, 0x38, 0x9c, 0x1b, 0x11, 0xbd, 0x63, 0xe5, 0x32, 0x1d, 0xcb, 0x87, 0x8a, 0x6c, 0x4c, 0x9c,
	0x2f, 0xba, 0xab, 0x41, 0x23, 0x77, 0x58, 0xff, 0x8b, 0x46, 0x34, 0x61, 0xae, 0x39, 0xea, 0x0c,
	0x1a, 0x8d, 0xad, 0x07, 0x62, 0xc9, 0x08, 0x04, 0x2b, 0xf0, 0x12, 0x29, 0x86, 0x3a, 0x84, 0x75,
	0x51, 0xf2, 0xf5, 0x68, 0xff, 0xfb, 0xfe, 0xaa, 0x41, 0xc8, 0x9b, 0x10, 0xea, 0x40, 0x74, 0x87,
	0x08, 0xe3, 0x57, 0x07, 0xdc, 0x94, 0xfc, 0xce, 0x04, 0x9b, 0x17, 0xce, 0x29, 0x80, 0xf9, 0x77,
	0x00, 0x2c, 0x98, 0x00, 0xaf, 0xc2, 0xb6, 0x05, 0x09, 0xe2, 0x7c, 0x00, 0x6b, 0x82, 0x39, 0x17,
	0xde, 0xcc, 0x4c, 0xf4, 0x37, 0x64, 0xb8, 0x75, 0xa3, 0xd7, 0xa1, 0xda, 0xa2, 0x89, 0x69, 0x31,
	0x49, 0x2d, 0x26, 0xfd, 0x91, 0xff, 0x35, 0xd4, 0xa4, 0x08, 0x26, 0xe7, 0x1d, 0x28, 0xe2, 0x75,
	0xc2, 0xe4, 0xb4, 0xdc, 0x33, 0x29, 0xe1, 0x7f, 0xa4, 0x47, 0xf7, 0xf1, 0xe5, 0x77, 0x17, 0x34,
	0xba, 0x9c, 0x72, 0x96, 0x97, 0xce, 0x8c, 0x08, 0x28, 0x69, 0x04, 0xbb, 0x07, 0xe4, 0xe9, 0x38,
	0x4e, 0x32, 0x46, 0x2c, 0x95, 0xda, 0xff, 0xc3, 0x81, 0x0d, 0x43, 0x14, 0x91, 0x37, 0x61, 0x45,
	0xae, 0xb1, 0x2c, 0xef, 0x21, 0x74, 0x8b, 0xf4, 0xbe, 0x5c, 0x88, 0x2a, 0xa8, 0x34, 0xbd, 0x2f,
	0xa1, 0x6a, 0xb0, 0x16, 0x2a, 0x66, 0x2f, 0x80, 0xb4, 0x28, 0x2f, 0x3d, 0xed, 0xc9, 0xcb, 0xf0,
	0xbd, 0xa5, 0xbd, 0x7f, 0x9b, 0x4f, 0x7c, 0xa9, 0x5d, 0x3c, 0x31, 0x81, 0x02, 0xdb, 0x63, 0x43,
	0xe6, 0x6b, 0xff, 0x7b, 0xf9, 0x49, 0x58, 0xac, 0x32, 0xd1, 0xdc, 0x81, 0x12, 0xdf, 0x6b, 0x21,
	0x4d, 0x09, 0xe4, 0x1a, 0x40, 0x40, 0x5f, 0x87, 0x6f, 0xa8, 0x6a, 0xcd, 0xa5, 0x40, 0xa3, 0xa4,
	0x9f, 0xcf, 0xb0, 0x8c, 0x9f, 0xef, 0x04, 0x36, 0x45, 0x05, 0x58, 0xcc, 0xa7, 0x0b, 0x45, 0x54,
	0x43, 0x87, 0x72, 0xcb, 0xe6, 0xd2, 0xac, 0x41, 0x74, 0xf5, 0x9b, 0x03, 0x75, 0x64, 0xf5, 0xc2,
	0xf7, 0x5b, 0x5e, 0x3c, 0x58, 0x61, 0xb9, 0xa2, 0x9a, 0x70, 0x29, 0x50, 0xfb, 0x39, 0x37, 0xfb,
	0x81, 0x3a, 0xbb, 0xc4, 0x93, 0x16, 0xfa, 0x26, 0x2f, 0xe6, 0xd6, 0xc1, 0x51, 0xf2, 0xfc, 0xdf,
	0x1d, 0x3d, 0xb2, 0xac, 0x34, 0xfc, 0x17, 0x4e, 0xf5, 0x04, 0x3c, 0x1b, 0xa8, 0x85, 0x8e, 0xd6,
	0x78, 0x5b, 0x85, 0xa5, 0x27, 0x8c, 0x4e, 0x9e, 0xf1, 0x4a, 0xa3, 0x8d, 0xc7, 0x64, 0x07, 0x35,
	0xac, 0x8f, 0x1c, 0xef, 0x7f, 0x33, 0xb8, 0xe8, 0xbf, 0x05, 0x15, 0x7d, 0x48, 0x26, 0x5e, 0x2a,
	0x9e, 0x1d, 0xfd, 0xbd, 0xab, 0x56, 0x1e, 0x1a, 0x7a, 0x06, 0xb5, 0xae, 0x1d, 0x57, 0x77, 0x2e,
	0xae, 0xee, 0x4c, 0x5c, 0x5d, 0x1b, 0xae, 0xee, 0x1c, 0x5c, 0xb6, 0x57, 0x16, 0xf9, 0x86, 0x7d,
	0x5a, 0x39, 0x81, 0xeb, 0x96, 0x2c, 0x73, 0xb9, 0xb2, 0x64, 0x1d, 0xfa, 0x3f, 0x67, 0x6f, 0x4f,
	0xf6, 0x44, 0x21, 0x75, 0xf5, 0x8d, 0xb4, 0xd7, 0x8d, 0xb7, 0x99, 0xa1, 0xa2, 0x5a, 0x83, 0x7d,
	0x39, 0x3a, 0x38, 0x25, 0x1b, 0xc8, 0xd7, 0x1f, 0x97, 0x5e, 0xdd, 0x24, 0xa2, 0xce, 0x03, 0x28,
	0xa9, 0x71, 0x93, 0x5c, 0x99, 0x1e, 0x40, 0x85, 0xae, 0x3b, 0x6b, 0x32, 0x65, 0x50, 0xc5, 0x23,
	0x40, 0x41, 0x35, 0xde, 0x04, 0x0a, 0xaa, 0xf9, 0x86, 0x25, 0xf7, 0xa1, 0x88, 0x13, 0x3e, 0x91,
	0x12, 0xe6, 0xc4, 0xef, 0x6d, 0x65, 0xc9, 0xa9, 0x26, 0x4e, 0x67, 0x4a, 0xd3, 0x9c, 0x10, 0x95,
	0x66, 0x76, 0x88, 0x7b, 0xa1, 0x0f, 0x38, 0x58, 0xa2, 0xc8, 0xff, 0xa5, 0x9b, 0x19, 0x4d, 0xd1,
	0xdb, 0x9d, 0x2d, 0xa0, 0xba, 0x58, 0x59, 0x6b, 0x57, 0x64, 0xdb, 0xd6, 0xc2, 0x84, 0x2d, 0x6f,
	0x76, 0x77, 0x4b, 0xd1, 0x69, 0x05, 0x34, 0x83, 0x6e, 0xba, 0x56, 0x67, 0xd0, 0x59, 0x6a, 0x2f,
	0xbb, 0x2d, 0x66, 0x55, 0x56, 0xb7, 0xc5, 0x5a, 0xfd, 0xd5, 0x6d, 0xb1, 0x97, 0x72, 0xf2, 0xad,
	0x9c, 0x70, 0xb1, 0x72, 0x92, 0xab, 0xa6, 0xbc, 0x51, 0xdf, 0xbd, 0x1d, 0x3b, 0x13, 0x6d, 0xfd,
	0x20, 0x07, 0x40, 0xbd, 0x5e, 0x91, 0xe9, 0x23, 0x65, 0xea, 0xab, 0x77, 0x7d, 0x8e, 0x44, 0x9a,
	0x96, 0xc2, 0xa7, 0x4a, 0x4b, 0x63, 0x2e, 0xf7, 0x36, 0x33, 0x54, 0x5b, 0x8a, 0xe0, 0xc4, 0x67,
	0x49, 0x11, 0x73, 0x2a, 0xb5, 0xa4, 0x48, 0x66, 0x58, 0x24, 0x87, 0x00, 0x29, 0x93, 0xb8, 0x53,
	0xf2, 0xd2, 0xd2, 0xb6, 0x85, 0x83, 0x26, 0xee, 0xc1, 0xb2, 0x98, 0xfb, 0xd4, 0x89, 0x8c, 0x49,
	0x51, 0x9d, 0xc8, 0x1c, 0x0e, 0x3f, 0x71, 0xd8, 0x0d, 0x57, 0x81, 0x52, 0x37, 0x3c, 0x3b, 0xba,
	0x7a, 0xee, 0x34, 0x03, 0x1d, 0x3f, 0x82, 0x22, 0x4e, 0x32, 0x2a, 0xb5, 0xa7, 0x27, 0x26, 0xcf,
	0xb3, 0xb1, 0xd0, 0x42, 0x07, 0x56, 0x33, 0xef, 0x3b, 0x22, 0xb3, 0xcc, 0xfe, 0x90, 0xf4, 0xae,
	0xcd, 0x62, 0x0b, 0x8b, 0x8f, 0x4b, 0x3f, 0x16, 0xf7, 0xc5, 0xef, 0xcb, 0x9f, 0x96, 0xf9, 0xff,
	0xcb, 0x4f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x78, 0x21, 0x5b, 0xdb, 0x14, 0x00, 0x00,
}
